ProjeCv/Controllers/HakkimdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCv.Models.Entity;
using ProjeCv.Models.Class;

namespace ProjeCv.Controllers
{
    public class HakkimdaController : Controller
    {
        // GET: Hakkimda

        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger1 = db.TblAbout.ToList();
            return View(cs);
        }

        public ActionResult HakkimdaGetir(int id)
        {
            var hakkimda = db.TblAbout.Find(id);

            return View("HakkimdaGetir", hakkimda);
        }


        public ActionResult HakkimdaGuncelle(TblAbout p)
        {
            var hakkimda = db.TblAbout.Find(p.Id);

           // hakkimda.Id = p.Id;
            hakkimda.Name = p.Name;
            hakkimda.Surname = p.Surname;
            hakkimda.Phone = p.Phone;
            hakkimda.Address = p.Address;
            hakkimda.Mail = p.Mail;
            hakkimda.About = p.About;

            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjeCv/Views/Hakkimda/HakkimdaGetir.cshtml
@model ProjeCv.Models.Entity.TblAbout
@{
    ViewBag.Title = "HakkimdaGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>HakkimdaGetir</h2>

@using (Html.BeginForm("HakkimdaGuncelle", "Hakkimda", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(i => i.Id)
        @Html.TextBoxFor(i => i.Id, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Name)
        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Surname)
        @Html.TextBoxFor(i => i.Surname, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Address)
        @Html.TextBoxFor(i => i.Address, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Phone)
        @Html.TextBoxFor(i => i.Phone, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Mail)
        @Html.TextBoxFor(i => i.Mail, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.About)
        @Html.TextAreaFor(i => i.About, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>


}

ProjeCv/Views/Hakkimda/Index.cshtml
@model ProjeCv.Models.Class.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                AD
            </th>
            <th>
                SOYAD
            </th>
            <th>
                ADRES
            </th>
            <th>
                TELEFON
            </th>
            <th>
                MAIL
            </th>
            @*  <th>
                    HAKKIMDA
                </th>
            </tr>*@
            <th>GÜNCELLE</th>
        </thead>
        <tbody>
            @foreach (var item in Model.Deger1)
            {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Address</td>
                <td>@item.Phone</td>
                <td>@item.Mail</td>
                @* <td>@item.About</td>*@
                <td><a href="/Hakkimda/HakkimdaGetir/@item.Id" class="btn btn-warning">Güncelle</a></td>
        </tr>
        }

    </tbody>
</table>