ProjeCv/Controllers/DeneyimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCv.Models.Entity;
using ProjeCv.Models.Class;
namespace ProjeCv.Controllers
{
    public class DeneyimlerController : Controller
    {
        // GET: Deneyimler

        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger2 = db.TblExperience.ToList();
            return View(cs);
        }
        [HttpGet]
        public ActionResult YeniDeneyim()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniDeneyim(TblExperience p)
        {
            db.TblExperience.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult DeneyimSil (int id)
        {
            var deneyim = db.TblExperience.Find(id);

            db.TblExperience.Remove(deneyim);
            db.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult DeneyimGetir(int id)
        {
            var deneyim = db.TblExperience.Find(id);

            return View("DeneyimGetir", deneyim);
        }

        public ActionResult DeneyimGuncelle(TblExperience p)
        {
            var deneyim = db.TblExperience.Find(p.Id);

            deneyim.Title = p.Title;
            deneyim.SubTitle = p.SubTitle;
            deneyim.Date = p.Date;
            deneyim.Details = p.Details;

            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjeCv/Views/Deneyimler/DeneyimGetir.cshtml
@model ProjeCv.Models.Entity.TblExperience
@{
    ViewBag.Title = "DeneyimGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("DeneyimGuncelle", "Deneyimler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(i => i.Id)
        @Html.TextBoxFor(i => i.Id, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Title)
        @Html.TextBoxFor(i => i.Title, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.SubTitle)
        @Html.TextBoxFor(i => i.SubTitle, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Date)
        @Html.TextBoxFor(i => i.Date, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Details)
        @Html.TextAreaFor(i => i.Details, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCv/Views/Deneyimler/Index.cshtml
@model ProjeCv.Models.Class.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                BAŞLIK
            </th>
            <th>
                ALT BAŞLIK
            </th>
            <th>
                TARİH
            </th>
            <th>
                DETAYLAR
            </th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
    </thead>
    <tbody>
        @foreach (var item in Model.Deger2)
        {
        <tr>
            <th>@item.Id</th>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.Date</td>
            <td>@item.Details</td>
            <td><a href="/Deneyimler/DeneyimSil/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Deneyimler/DeneyimGetir/@item.Id" class="btn btn-success">Güncelle</a></td>
        </tr>
        }

    </tbody>
</table>

<a href="/Deneyimler/YeniDeneyim" class="btn btn-info" >Yeni Deneyim Ekle</a>

ProjeCv/Views/Deneyimler/YeniDeneyim.cshtml
@{
    ViewBag.Title = "YeniDeneyim";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Deneyim Başlığı</label>
        <input type="text" class="form-control" name="Title" />
    </div>
    <br />
    <div>
        <label>Deneyim Alt Başlığı</label>
        <input type="text" class="form-control" name="SubTitle" />
    </div>
    <br />
    <div>
        <label>Tarih</label>
        <input type="text" class="form-control" name="Date" />
    </div>
    <br />
    <div>
        <label>Detaylar</label>
       <textarea class="form-control" rows="10" name="Details"></textarea>
    </div>
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>