ProjeCv/Controllers/HobilerController.cs
using ProjeCv.Models.Class;
using ProjeCv.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeCv.Controllers
{
    public class HobilerController : Controller
    {
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger5 = db.TblInterests.ToList();
            return View(cs);
        }

        [HttpGet]
        public ActionResult YeniHobi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniHobi(TblInterests p)
        {
            db.TblInterests.Add(p);
            db.SaveChanges();
            return View(p);
        }

        public ActionResult HobiSil(int id)
        {
            var hobi = db.TblInterests.Find(id);

            db.TblInterests.Remove(hobi);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult HobiGetir(int id)
        {
            var hobi = db.TblInterests.Find(id);

            return View("HobiGetir", hobi);
        }

        public ActionResult HobiGuncelle(TblInterests p)
        {
            var hobi = db.TblInterests.Find(p.Id);

            hobi.Interest = p.Interest;

            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjeCv/Views/Hobiler/HobiGetir.cshtml
@model ProjeCv.Models.Entity.TblInterests
@{
    ViewBag.Title = "HobiGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("HobiGuncelle", "Hobiler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(i => i.Id)
        @Html.TextBoxFor(i => i.Id, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Interest)
        @Html.TextBoxFor(i => i.Interest, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCv/Views/Hobiler/Index.cshtml
@model ProjeCv.Models.Class.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                HOBİLER
            </th>
            <th>SİL</th>
            <td>GÜNCELLE</td>
    </thead>
    <tbody>
        @foreach (var item in Model.Deger5)
        {
            <tr>
                <th>@item.Id</th>
                <td>@item.Interest</td>
                <td>@Html.ActionLink("Hobi Sil", "HobiSil", new { id = item.Id }, new { @class = "btn btn-danger", onclick = "return confirm ('Silmek İstiyor Musun?')" })</td>
                <td><a href="/Hobiler/HobiGetir/@item.Id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }

    </tbody>
</table>

<a href="/Hobiler/YeniHobi" class="btn btn-info">Yeni Hobi Ekle</a>

ProjeCv/Views/Hobiler/YeniHobi.cshtml
@{
    ViewBag.Title = "YeniHobi";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<form class="form-group" method="post">
    <div>
        <label>Hobi</label>
        <input type="text" class="form-control" name="Interest" />
    </div>
    <br />

    <button class="btn btn-primary">Kaydet</button>
</form>