ProjeCv/Controllers/EgitimlerController.cs
using ProjeCv.Models.Class;
using ProjeCv.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeCv.Controllers
{
    public class EgitimlerController : Controller
    {
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger3 = db.TblEducation.ToList();
            return View(cs);
        }

        [HttpGet]
        public ActionResult YeniEgitim()
        {
            return View();
        }

        public ActionResult YeniEgitim(TblEducation p)
        {
            db.TblEducation.Add(p);
            db.SaveChanges();
            return View();
        }

        public ActionResult EgitimSil(int id)
        {
            var egitim = db.TblEducation.Find(id);

            db.TblEducation.Remove(egitim);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult EgitimGetir(int id)
        {
            var egitim = db.TblEducation.Find(id);

            return View("EgitimGetir", egitim);
        }

        public ActionResult EgitimGuncelle(TblEducation p)
        {
            var egitim = db.TblEducation.Find(p.Id);

            egitim.Title = p.Title;
            egitim.SubTitle = p.SubTitle;
            egitim.Department = p.Department;
            egitim.Gpa = p.Gpa;


            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjeCv/Views/Egitimler/EgitimGetir.cshtml
@model ProjeCv.Models.Entity.TblEducation
@{
    ViewBag.Title = "EgitimGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("EgitimGuncelle", "Egitimler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(i => i.Id)
        @Html.TextBoxFor(i => i.Id, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Title)
        @Html.TextBoxFor(i => i.Title, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.SubTitle)
        @Html.TextBoxFor(i => i.SubTitle, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Department)
        @Html.TextBoxFor(i => i.Department, new { @class = "form-control" })
        <br />
        @Html.LabelFor(i => i.Gpa)
        @Html.TextBoxFor(i => i.Gpa, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCv/Views/Egitimler/Index.cshtml
@model ProjeCv.Models.Class.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                BAŞLIK
            </th>
            <th>
                ALT BAŞLIK
            </th>
            <th>
                BÖLÜM
            </th>
            <th>
                DNO
            </th>
            <th>SİL</th>
            <th>GÜNCELLEME</th>
</thead>
    <tbody>
        @foreach (var item in Model.Deger3)
        {
        <tr>
            <th>@item.Id</th>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.Department</td>
            <td>@item.Gpa</td>
            <td><a href="/Egitimler/EgitimSil/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Egitimler/EgitimGetir/@item.Id" class="btn btn-success">Güncelle</a></td>
        </tr>
        }

    </tbody>
</table>

<a href="/Egitimler/YeniEgitim" class="btn btn-info">Yeni Eğitim Ekle</a>

ProjeCv/Views/Egitimler/YeniEgitim.cshtml
@{
    ViewBag.Title = "YeniEgitim";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Okul</label>
        <input type="text" class="form-control" name="Title" />
    </div>
    <br />
    <div>
        <label>Fakülte</label>
        <input type="text" class="form-control" name="SubTitle" />
    </div>
    <br />
    <div>
        <label>Bölüm</label>
        <input type="text" class="form-control" name="Department" />
    </div>
    <br />
    <div>
        <label>Genel Not Ortalaması</label>
        <input type="text" class="form-control" name="Gpa" />
    </div>
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>